Add stub for Symfony AbstractType
phpstan/phpstan-symfony pull request #317
Opened 2022-12-18 00:22 UTC by gndk

This PR adds stubs for `Symfony\Component\Form\AbstractType` and `Symfony\Component\Form\AbstractTypeExtension`.

After upgrading to Psalm 5, it requires `@template-extends AbstractType<int>` annotation when extending `AbstractType`, but currently phpstan complains about this. 

Adding these stubs creates parity with [psalm/psalm-plugin-symfony](https://github.com/psalm/psalm-plugin-symfony/tree/5.x/src/Stubs/common/Component/Form) regarding those classes.

2022-12-19 14:23 UTC, stof commented
what is expected to be represented by that template type ?

2022-12-19 17:06 UTC, gndk commented
The stubs in the psalm plugin were originally added in this PR https://github.com/psalm/psalm-plugin-symfony/pull/138, with some discussion here https://github.com/psalm/psalm-plugin-symfony/issues/60.

2022-12-19 17:21 UTC, gndk commented
There is also discussion around this on the psalm plugin here https://github.com/psalm/psalm-plugin-symfony/issues/294

2022-12-22 14:52 UTC, VincentLanglet requested changes
Those stubs are useless for PHPStan and even more they will just add more pain for PHPStan-Symfony user because it will require to fill a template
```
/**
 * @extends AbstractType<ICanWriteEverythingIWant>
 */
class MyType extends AbstractType
{
}
```
With no benefit at all.

@stof Those stubs were added to psalm-symfony with only one benefit, this one:
https://github.com/psalm/psalm-plugin-symfony/blob/4.x/src/Stubs/common/Component/Form/FormView.stubphp#L16
but the syntax `array{value: ?T, attr: array<array-key, mixed>}&array<string, mixed>`
is not supported by PHPStan.

So there is absolutely no reason to add such template.

Also the symfony-core was not really into those generics https://github.com/symfony/symfony/pull/40783#issuecomment-953098461

If you want to use both psalm and phpstan, I assume you can write
```
/** 
 * @psalm-param FormView<Foo>
 * @phpstan-param FormView
 */
```

2022-12-22 16:02 UTC, closed without merging