Introduce Voter stub
phpstan/phpstan-symfony pull request #326
Opened 2023-01-19 11:58 UTC by VincentLanglet

Does such a stub require a test ?

2023-01-19 12:00 UTC, ondrejmirtes commented
I'm not sure that everyone who `extends Voter` wants this functionality. In case they do, try introducing these generics into Symfony directly.

2023-01-19 12:15 UTC, VincentLanglet commented
> I'm not sure that everyone who `extends Voter` wants this functionality.

Same could be said for almost every stub I would say.
For instance I get lot of trouble with this stub https://github.com/phpstan/phpstan-symfony/issues/322

I don't consider this stub as an hack or a wrong stub.
And I thought this was one of the purpose of `skipCheckGenericClasses`, people can skip this stub.
Or just `Voter<string, mixed>` will do nothing.

> In case they do, try introducing these generics into Symfony directly.

Symfony is a kinda slow adopter about new annotations as shown in https://github.com/symfony/symfony/pull/46613
Also, they only accepts such things on new branch, which means it would be only available on Sf 6.3.

But I can start by this to get feedback and decide after for phpstan-symfony, sure. 👍

2023-01-26 16:32 UTC, VincentLanglet commented
> I'm not sure that everyone who extends Voter wants this functionality. In case they do, try introducing these generics into Symfony directly.

Hi @ondrejmirtes, the template was accepted by symfony in 6.3 https://github.com/symfony/symfony/pull/49033
Do we merge this to add the template in older symfony version ?

2023-01-31 08:09 UTC, ondrejmirtes requested changes

2023-01-31 08:09 UTC, ondrejmirtes commented on stubs/Symfony/Component/Security/Core/Authorization/Voter/Voter.stub
> +	 * @phpstan-assert-if-true TSubject $subject
Wrong formatting

2023-01-31 11:42 UTC, VincentLanglet commented on stubs/Symfony/Component/Security/Core/Authorization/Voter/Voter.stub
> +	 * @phpstan-assert-if-true TSubject $subject
Nice catch, fixed.

2023-01-31 15:20 UTC, ondrejmirtes approved these changes

2023-01-31 15:20 UTC, merged

2023-01-31 15:20 UTC, ondrejmirtes commented
Thank you.