Add stubs for security factories
phpstan/phpstan-symfony pull request #342
Opened 2023-03-23 13:45 UTC by yguedidi

2023-03-27 13:48 UTC, ondrejmirtes requested changes

2023-03-27 13:48 UTC, ondrejmirtes commented on stubs/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/AuthenticatorFactoryInterface.stub
> +     * @return string|string[]
When does it return a string and when does it return an array?

2023-03-27 22:22 UTC, yguedidi commented on stubs/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/AuthenticatorFactoryInterface.stub
> +     * @return string|string[]
It depends on the concrete implementation, for example:

- string: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/AccessTokenFactory.php#L70
- array: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/CustomAuthenticatorFactory.php#L60

2023-03-29 13:09 UTC, stof commented on stubs/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/AuthenticatorFactoryInterface.stub
> +     * @return string|string[]
Returning a string is treated the same than returning an array containing a single item by the Symfony code calling this factory. It allows to simplify the most common case which only needs to create a single authenticator.

2023-04-03 16:57 UTC, yguedidi commented on stubs/Symfony/Bundle/SecurityBundle/DependencyInjection/Security/Factory/AuthenticatorFactoryInterface.stub
> +     * @return string|string[]
@ondrejmirtes is there anything else I can do?

2023-04-04 08:12 UTC, stof approved these changes

2023-04-05 12:16 UTC, merged

2023-04-05 12:16 UTC, ondrejmirtes commented
Thank you!

2023-04-05 12:16 UTC, ondrejmirtes commented
Thank you!